# Generated by Django 5.2.8 on 2025-11-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="raw_message",
            field=models.TextField(
                blank=True, help_text="Full raw email message including headers"
            ),
        ),
    ]
