# Generated by Django 5.2.8 on 2026-02-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_entry_raw_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="core_team",
            field=models.ManyToManyField(
                blank=True, related_name="core_team_boards", to="core.correspondent"
            ),
        ),
    ]
