# Generated by Django 5.2.8 on 2026-09-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_board_core_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="source_filename",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Maildir unique id this entry was imported from, without the flag suffix. Set lazily by the review_emails command so later runs can skip the file without reading it.",
                max_length=255,
            ),
        ),
    ]
